version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: db-proyecto-tecnologico
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: isil_pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@isil.pe
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - postgres-db

  api:
    build: . 
    container_name: isil_express_container
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres-db
    environment:
      PORT: 3000
      DATABASE_URL: "postgres://postgres:postgres@postgres-db:5432/postgres"

volumes:
  postgres_data:
