/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FormatoRouteImport } from './routes/formato'
import { Route as FranquiciaRouteImport } from './routes/franquicia'
import { Route as MarcaIndexRouteImport } from './routes/marca/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatoRoute = FormatoRouteImport.update({
  id: '/formato',
  path: '/formato',
  getParentRoute: () => rootRouteImport,
} as any)
const FranquiciaRoute = FranquiciaRouteImport.update({
  id: '/franquicia',
  path: '/franquicia',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaIndexRoute = MarcaIndexRouteImport.update({
  id: '/marca/',
  path: '/marca/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/formato': typeof FormatoRoute
  '/franquicia': typeof FranquiciaRoute
  '/marca/': typeof MarcaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/formato': typeof FormatoRoute
  '/franquicia': typeof FranquiciaRoute
  '/marca': typeof MarcaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/formato': typeof FormatoRoute
  '/franquicia': typeof FranquiciaRoute
  '/marca/': typeof MarcaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/formato' | '/franquicia' | '/marca/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/formato' | '/franquicia' | '/marca'
  id: '__root__' | '/' | '/about' | '/formato' | '/franquicia' | '/marca/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FormatoRoute: typeof FormatoRoute
  FranquiciaRoute: typeof FranquiciaRoute
  MarcaIndexRoute: typeof MarcaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formato': {
      id: '/formato'
      path: '/formato'
      fullPath: '/formato'
      preLoaderRoute: typeof FormatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franquicia': {
      id: '/franquicia'
      path: '/franquicia'
      fullPath: '/franquicia'
      preLoaderRoute: typeof FranquiciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca/': {
      id: '/marca/'
      path: '/marca'
      fullPath: '/marca/'
      preLoaderRoute: typeof MarcaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FormatoRoute: FormatoRoute,
  FranquiciaRoute: FranquiciaRoute,
  MarcaIndexRoute: MarcaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
